/**
 * Pure layout tree operations for split tab groups.
 *
 * Every function here is side-effect-free and returns a new tree.
 * Node ids are NEVER regenerated by normalize — React keys depend on stability.
 *
 * @module panelLayout
 */

import type {
  PanelGroupNode,
  PanelLayoutNode,
  SessionPanelLayout,
  ToolPanel,
} from '../../../shared/types/panels';

interface ReconciledPanelLayout {
  layout: SessionPanelLayout;
  changed: boolean;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function newId(): string {
  return crypto.randomUUID();
}

/** Find the first group in reading order (leftmost / topmost leaf). */
export function primaryGroup(root: PanelLayoutNode): PanelGroupNode {
  if (root.type === 'group') return root;
  return primaryGroup(root.children[0]);
}

/** Collect all group nodes in reading order (depth-first, children left-to-right). */
export function allGroups(root: PanelLayoutNode): PanelGroupNode[] {
  if (root.type === 'group') return [root];
  return root.children.flatMap(allGroups);
}

/** Collect all panel ids referenced by the layout tree. */
export function allPanelIds(root: PanelLayoutNode): string[] {
  if (root.type === 'group') return [...root.panelIds];
  return root.children.flatMap(allPanelIds);
}

/** Find a group node by id. */
export function findGroup(root: PanelLayoutNode, groupId: string): PanelGroupNode | null {
  if (root.type === 'group') return root.id === groupId ? root : null;
  for (const child of root.children) {
    const found = findGroup(child, groupId);
    if (found) return found;
  }
  return null;
}

/** Check whether a subtree contains a given group id. */
export function containsGroup(node: PanelLayoutNode, groupId: string): boolean {
  if (node.type === 'group') return node.id === groupId;
  return node.children.some(c => containsGroup(c, groupId));
}

/** Find which group contains a given panelId. */
export function findGroupContainingPanel(root: PanelLayoutNode, panelId: string): PanelGroupNode | null {
  if (root.type === 'group') return root.panelIds.includes(panelId) ? root : null;
  for (const child of root.children) {
    const found = findGroupContainingPanel(child, panelId);
    if (found) return found;
  }
  return null;
}

/** Activate a panel and focus its containing group without changing the tree structure. */
export function activatePanelInLayout(
  layout: SessionPanelLayout,
  panelId: string,
): SessionPanelLayout {
  const group = findGroupContainingPanel(layout.root, panelId);
  if (!group) return layout;
  const groupId = group.id;

  function activate(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      return node.id === groupId ? { ...node, activePanelId: panelId } : node;
    }
    return { ...node, children: node.children.map(activate) };
  }

  return {
    ...layout,
    root: activate(layout.root),
    focusedGroupId: groupId,
    zoomedGroupId: layout.zoomedGroupId && layout.zoomedGroupId !== groupId
      ? null
      : layout.zoomedGroupId,
  };
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/** Create a single-group layout from an ordered list of panel ids. */
export function createSingleGroupLayout(
  panelIds: string[],
  activePanelId: string | null,
): SessionPanelLayout {
  const groupId = newId();
  return {
    version: 1,
    root: {
      type: 'group',
      id: groupId,
      panelIds,
      activePanelId: activePanelId && panelIds.includes(activePanelId) ? activePanelId : panelIds[0] ?? null,
    },
    focusedGroupId: groupId,
  };
}

/**
 * Add a panel to a group. Idempotent: if the panel id already exists anywhere
 * in the tree, the tree is returned unchanged. This guards against the
 * create-path double-append (handlePanelCreate and the panel:created event
 * both try to insert the same panel).
 */
export function addPanelToGroup(
  root: PanelLayoutNode,
  groupId: string,
  panelId: string,
  options: { activate?: boolean } = {},
): PanelLayoutNode {
  if (allPanelIds(root).includes(panelId)) return root;
  const activate = options.activate !== false;

  function insert(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (node.id !== groupId) return node;
      const activePanelId = activate || !node.activePanelId
        ? panelId
        : node.activePanelId;
      return {
        ...node,
        panelIds: [...node.panelIds, panelId],
        activePanelId,
      };
    }
    return { ...node, children: node.children.map(insert) };
  }

  return insert(root);
}

/**
 * Open a panel beside the primary group: as a tab in the last other group, or
 * in a new right-hand group when the layout has only one. Idempotent like
 * addPanelToGroup.
 */
export function placePanelInSplit(root: PanelLayoutNode, panelId: string, activate = true): PanelLayoutNode {
  if (allPanelIds(root).includes(panelId)) return root;
  const primary = primaryGroup(root);
  const side = allGroups(root).filter(group => group.id !== primary.id).pop();
  return side
    ? addPanelToGroup(root, side.id, panelId, { activate })
    : splitGroup(root, primary.id, panelId, 'row', true);
}

// ---------------------------------------------------------------------------
// Normalize
// ---------------------------------------------------------------------------

/**
 * Normalize the tree:
 * - Drop empty groups.
 * - Replace single-child splits with the child.
 * - Merge same-direction nested splits (flatten).
 * - Renormalize sizes to sum 1.
 * CRITICAL: preserve every surviving node's id.
 */
export function normalize(root: PanelLayoutNode): PanelLayoutNode {
  if (root.type === 'group') return root;

  // Recurse children first
  let children: PanelLayoutNode[] = [];
  let sizes: number[] = [];
  for (let i = 0; i < root.children.length; i++) {
    const child = normalize(root.children[i]);
    // Drop empty groups
    if (child.type === 'group' && child.panelIds.length === 0) continue;
    children.push(child);
    sizes.push(root.sizes[i] ?? 1);
  }

  // If no children remain, return an empty group (caller should handle)
  if (children.length === 0) {
    return { type: 'group', id: root.id, panelIds: [], activePanelId: null };
  }

  // Single child: unwrap
  if (children.length === 1) return children[0];

  // Flatten same-direction nested splits
  const flatChildren: PanelLayoutNode[] = [];
  const flatSizes: number[] = [];
  const totalSize = sizes.reduce((a, b) => a + b, 0) || 1;
  for (let i = 0; i < children.length; i++) {
    const child = children[i];
    const childProportion = sizes[i] / totalSize;
    if (child.type === 'split' && child.direction === root.direction) {
      const childTotal = child.sizes.reduce((a, b) => a + b, 0) || 1;
      for (let j = 0; j < child.children.length; j++) {
        flatChildren.push(child.children[j]);
        flatSizes.push(childProportion * (child.sizes[j] / childTotal));
      }
    } else {
      flatChildren.push(child);
      flatSizes.push(childProportion);
    }
  }

  children = flatChildren;
  sizes = flatSizes;

  // Renormalize sizes to sum 1
  const sizeSum = sizes.reduce((a, b) => a + b, 0) || 1;
  sizes = sizes.map(s => s / sizeSum);

  return { ...root, children, sizes };
}

// ---------------------------------------------------------------------------
// Split
// ---------------------------------------------------------------------------

/**
 * Split a group: move `panelId` out of `sourceGroupId` into a new sibling group.
 *
 * N-ary rule: if the parent split already runs in `direction`, insert as a sibling
 * (no nesting). Only wrap in a new split node when the direction differs or
 * the group is the root.
 */
export function splitGroup(
  root: PanelLayoutNode,
  sourceGroupId: string,
  panelId: string,
  direction: 'row' | 'column',
  after = true,
): PanelLayoutNode {
  const newGroupId = newId();
  const newGroup: PanelGroupNode = {
    type: 'group',
    id: newGroupId,
    panelIds: [panelId],
    activePanelId: panelId,
  };

  function removePanel(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (node.id !== sourceGroupId) return node;
      const filtered = node.panelIds.filter(id => id !== panelId);
      return {
        ...node,
        panelIds: filtered,
        activePanelId: node.activePanelId === panelId
          ? (filtered[0] ?? null)
          : node.activePanelId,
      };
    }
    return {
      ...node,
      children: node.children.map(removePanel),
    };
  }

  function insertSibling(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group' && node.id === sourceGroupId) {
      // Source is the root or a leaf — wrap in a new split
      const splitId = newId();
      const equalSize = 0.5;
      const children = after ? [node, newGroup] : [newGroup, node];
      return {
        type: 'split',
        id: splitId,
        direction,
        children,
        sizes: [equalSize, equalSize],
      };
    }
    if (node.type === 'split') {
      const idx = node.children.findIndex(c => c.id === sourceGroupId);
      if (idx !== -1 && node.direction === direction) {
        // Same direction: insert as sibling in the existing split (n-ary)
        const newChildren = [...node.children];
        const newSizes = [...node.sizes];
        // Give the new group the same size as the source, then renormalize
        const sourceSize = newSizes[idx];
        const halfSize = sourceSize / 2;
        newSizes[idx] = halfSize;
        if (after) {
          newChildren.splice(idx + 1, 0, newGroup);
          newSizes.splice(idx + 1, 0, halfSize);
        } else {
          newChildren.splice(idx, 0, newGroup);
          newSizes.splice(idx, 0, halfSize);
        }
        return { ...node, children: newChildren, sizes: newSizes };
      }
      // Recurse into children
      return {
        ...node,
        children: node.children.map(insertSibling),
      };
    }
    return node;
  }

  // 1. Remove panelId from source group
  const afterRemove = removePanel(root);
  // 2. Insert the new group next to the source
  const afterInsert = insertSibling(afterRemove);
  // 3. Normalize
  return normalize(afterInsert);
}

// ---------------------------------------------------------------------------
// Move panel
// ---------------------------------------------------------------------------

export type DropZone = 'left' | 'right' | 'top' | 'bottom' | 'center';

interface MoveTargetCenter {
  groupId: string;
  index: number;
}

interface MoveTargetEdge {
  groupId: string;
  edge: 'left' | 'right' | 'top' | 'bottom';
}

export type MoveTarget = MoveTargetCenter | MoveTargetEdge;

function isCenterTarget(t: MoveTarget): t is MoveTargetCenter {
  return 'index' in t;
}

/**
 * Move a panel: center drop inserts into target group at index;
 * edge drop splits against the target.
 */
export function movePanel(
  root: PanelLayoutNode,
  panelId: string,
  target: MoveTarget,
): PanelLayoutNode {
  // Remove from source
  function removePanelFromTree(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (!node.panelIds.includes(panelId)) return node;
      const filtered = node.panelIds.filter(id => id !== panelId);
      return {
        ...node,
        panelIds: filtered,
        activePanelId: node.activePanelId === panelId
          ? (filtered[0] ?? null)
          : node.activePanelId,
      };
    }
    return { ...node, children: node.children.map(removePanelFromTree) };
  }

  if (isCenterTarget(target)) {
    // Center: insert into the target group at index. target.index is based on
    // the pre-removal tab order, so a same-group move to a later position must
    // shift left by one or it lands one slot past the drop indicator.
    const centerTarget = target;
    let insertIndex = centerTarget.index;
    const targetGroup = findGroup(root, centerTarget.groupId);
    if (targetGroup) {
      const sourceIdx = targetGroup.panelIds.indexOf(panelId);
      if (sourceIdx !== -1 && sourceIdx < insertIndex) insertIndex -= 1;
    }
    const removed = removePanelFromTree(root);
    function insertIntoGroup(node: PanelLayoutNode): PanelLayoutNode {
      if (node.type === 'group' && node.id === centerTarget.groupId) {
        const newPanelIds = [...node.panelIds];
        const insertIdx = Math.min(insertIndex, newPanelIds.length);
        newPanelIds.splice(insertIdx, 0, panelId);
        return { ...node, panelIds: newPanelIds, activePanelId: panelId };
      }
      if (node.type === 'split') {
        return { ...node, children: node.children.map(insertIntoGroup) };
      }
      return node;
    }
    return normalize(insertIntoGroup(removed));
  }

  // Edge: this is a split. Remove the panel, then split against the target group.
  const removed = removePanelFromTree(root);
  const normalized = normalize(removed);

  // SAFETY: The surrounding typed producer establishes the narrower value shape consumed here.
  const edgeTarget = target as MoveTargetEdge;
  const direction: 'row' | 'column' = (edgeTarget.edge === 'left' || edgeTarget.edge === 'right') ? 'row' : 'column';
  const after = edgeTarget.edge === 'right' || edgeTarget.edge === 'bottom';

  // We need to create a new group beside the target group
  const newGroupId = newId();
  const newGroup: PanelGroupNode = {
    type: 'group',
    id: newGroupId,
    panelIds: [panelId],
    activePanelId: panelId,
  };

  function insertBesideGroup(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group' && node.id === edgeTarget.groupId) {
      const splitId = newId();
      const children = after ? [node, newGroup] : [newGroup, node];
      return { type: 'split', id: splitId, direction, children, sizes: [0.5, 0.5] };
    }
    if (node.type === 'split') {
      const idx = node.children.findIndex(c => c.id === edgeTarget.groupId);
      if (idx !== -1 && node.direction === direction) {
        // N-ary: insert sibling
        const newChildren = [...node.children];
        const newSizes = [...node.sizes];
        const halfSize = newSizes[idx] / 2;
        newSizes[idx] = halfSize;
        if (after) {
          newChildren.splice(idx + 1, 0, newGroup);
          newSizes.splice(idx + 1, 0, halfSize);
        } else {
          newChildren.splice(idx, 0, newGroup);
          newSizes.splice(idx, 0, halfSize);
        }
        return { ...node, children: newChildren, sizes: newSizes };
      }
      return { ...node, children: node.children.map(insertBesideGroup) };
    }
    return node;
  }

  return normalize(insertBesideGroup(normalized));
}

// ---------------------------------------------------------------------------
// Remove panel from layout (for close)
// ---------------------------------------------------------------------------

/**
 * Remove a panel id from the layout. Returns null if the tree collapses entirely.
 */
export function removePanelFromLayout(
  root: PanelLayoutNode,
  panelId: string,
): PanelLayoutNode | null {
  function remove(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      if (!node.panelIds.includes(panelId)) return node;
      const filtered = node.panelIds.filter(id => id !== panelId);
      return {
        ...node,
        panelIds: filtered,
        activePanelId: node.activePanelId === panelId
          ? (filtered[0] ?? null)
          : node.activePanelId,
      };
    }
    return { ...node, children: node.children.map(remove) };
  }

  const result = normalize(remove(root));
  // If the entire tree collapsed to an empty group, return null
  if (result.type === 'group' && result.panelIds.length === 0) return null;
  return result;
}

// ---------------------------------------------------------------------------
// Reconcile
// ---------------------------------------------------------------------------

/**
 * Reconcile a stored layout against the current live panel ids.
 * - Prune panel ids not in livePanelIds.
 * - Append unassigned live panels to the primary group.
 * - Fix activePanelId per group.
 * - Guarantee at least one group.
 */
export function reconcile(
  layout: SessionPanelLayout,
  livePanelIds: string[],
  splitPanelIds: ReadonlySet<string> = new Set(),
): ReconciledPanelLayout {
  const liveSet = new Set(livePanelIds);
  let changed = false;
  // A panel id may only appear once across the whole tree; keep the first
  // occurrence in reading order and drop duplicates.
  const seen = new Set<string>();

  function cleanNode(node: PanelLayoutNode): PanelLayoutNode {
    if (node.type === 'group') {
      const filtered = node.panelIds.filter(id => {
        if (!liveSet.has(id) || seen.has(id)) { changed = true; return false; }
        seen.add(id);
        return true;
      });
      const active = filtered.includes(node.activePanelId ?? '') ? node.activePanelId : (filtered[0] ?? null);
      if (active !== node.activePanelId) changed = true;
      return { ...node, panelIds: filtered, activePanelId: active };
    }
    return { ...node, children: node.children.map(cleanNode) };
  }

  let root = normalize(cleanNode(layout.root));

  // If the tree collapsed, recreate with a single group
  if (root.type === 'group' && root.panelIds.length === 0 && livePanelIds.length > 0) {
    changed = true;
    root = {
      type: 'group',
      id: root.id,
      panelIds: [...livePanelIds],
      activePanelId: livePanelIds[0],
    };
  }

  // Find orphans (live panels not in the tree)
  const assigned = new Set(allPanelIds(root));
  const unassigned = livePanelIds.filter(id => !assigned.has(id));
  const orphans = unassigned.filter(id => !splitPanelIds.has(id));
  for (const id of unassigned) {
    if (!splitPanelIds.has(id)) continue;
    changed = true;
    root = placePanelInSplit(root, id);
  }
  if (orphans.length > 0) {
    changed = true;
    const primary = primaryGroup(root);
    // We need to mutate the tree to add orphans to the primary group
    function addOrphansToPrimary(node: PanelLayoutNode): PanelLayoutNode {
      if (node.type === 'group' && node.id === primary.id) {
        return {
          ...node,
          panelIds: [...node.panelIds, ...orphans],
          activePanelId: node.activePanelId ?? orphans[0],
        };
      }
      if (node.type === 'split') {
        return { ...node, children: node.children.map(addOrphansToPrimary) };
      }
      return node;
    }
    root = addOrphansToPrimary(root);
  }

  // Validate focusedGroupId
  let focusedGroupId = layout.focusedGroupId;
  if (!focusedGroupId || !findGroup(root, focusedGroupId)) {
    focusedGroupId = primaryGroup(root).id;
    changed = true;
  }

  // Validate zoomedGroupId
  let zoomedGroupId = layout.zoomedGroupId;
  if (zoomedGroupId && !findGroup(root, zoomedGroupId)) {
    zoomedGroupId = null;
    changed = true;
  }

  return {
    layout: { ...layout, root, focusedGroupId, zoomedGroupId },
    changed,
  };
}

// ---------------------------------------------------------------------------
// Merge all groups (the un-split gesture)
// ---------------------------------------------------------------------------

/**
 * Collapse the entire tree into the primary group. Panel order: the primary
 * group's panels first, then the remaining groups' panels in reading order.
 * The primary group's id and active tab survive.
 */
export function mergeAllGroups(root: PanelLayoutNode): PanelGroupNode {
  if (root.type === 'group') return root;
  const primary = primaryGroup(root);
  const seen = new Set<string>();
  const ids: string[] = [];
  for (const id of allPanelIds(root)) {
    if (!seen.has(id)) {
      seen.add(id);
      ids.push(id);
    }
  }
  return {
    type: 'group',
    id: primary.id,
    panelIds: ids,
    activePanelId: primary.activePanelId ?? ids[0] ?? null,
  };
}

// ---------------------------------------------------------------------------
// Subset index translation
// ---------------------------------------------------------------------------

/**
 * Translate an insertion index within a displayed subset of a group's tabs
 * (e.g. a strip showing only non-permanent tabs while the permanent ones stay
 * in the top bar) into an insertion index in the group's full panel order.
 * The subset must preserve the full order's relative ordering.
 */
export function subsetInsertIndex(
  fullIds: string[],
  subsetIds: string[],
  subsetIndex: number,
): number {
  if (subsetIndex >= subsetIds.length) {
    const last = subsetIds[subsetIds.length - 1];
    if (last === undefined) return fullIds.length;
    const i = fullIds.indexOf(last);
    return i === -1 ? fullIds.length : i + 1;
  }
  const i = fullIds.indexOf(subsetIds[subsetIndex]);
  return i === -1 ? fullIds.length : i;
}

// ---------------------------------------------------------------------------
// Update sizes
// ---------------------------------------------------------------------------

/**
 * Update the sizes array for a specific split node by id.
 */
export function updateSizes(
  root: PanelLayoutNode,
  splitNodeId: string,
  newSizes: number[],
): PanelLayoutNode {
  if (root.type === 'group') return root;
  if (root.id === splitNodeId) {
    return { ...root, sizes: newSizes };
  }
  return { ...root, children: root.children.map(c => updateSizes(c, splitNodeId, newSizes)) };
}

// ---------------------------------------------------------------------------
// Geometry (for directional focus)
// ---------------------------------------------------------------------------

export interface GroupRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Assign each group a rect in unit space [0,1]x[0,1]. */
export function groupRects(root: PanelLayoutNode): Map<string, GroupRect> {
  const result = new Map<string, GroupRect>();

  function walk(node: PanelLayoutNode, x: number, y: number, w: number, h: number) {
    if (node.type === 'group') {
      result.set(node.id, { x, y, w, h });
      return;
    }
    const totalSize = node.sizes.reduce((a, b) => a + b, 0) || 1;
    let offset = 0;
    for (let i = 0; i < node.children.length; i++) {
      const proportion = (node.sizes[i] ?? 1) / totalSize;
      if (node.direction === 'row') {
        walk(node.children[i], x + offset * w, y, proportion * w, h);
      } else {
        walk(node.children[i], x, y + offset * h, w, proportion * h);
      }
      offset += proportion;
    }
  }

  walk(root, 0, 0, 1, 1);
  return result;
}

/**
 * Find the nearest group in a direction from the focused group.
 * Uses geometric overlap: pick the group across the focused edge with max perpendicular overlap.
 */
export function findGroupInDirection(
  root: PanelLayoutNode,
  fromGroupId: string,
  dir: 'left' | 'right' | 'up' | 'down',
): string | null {
  const rects = groupRects(root);
  const from = rects.get(fromGroupId);
  if (!from) return null;

  const eps = 0.001;
  let best: string | null = null;
  let bestOverlap = -1;
  let bestDist = Infinity;

  for (const [gid, rect] of rects) {
    if (gid === fromGroupId) continue;

    let isCandidate = false;
    let overlap = 0;
    let dist = 0;

    switch (dir) {
      case 'right':
        isCandidate = rect.x >= from.x + from.w - eps;
        overlap = Math.max(0, Math.min(from.y + from.h, rect.y + rect.h) - Math.max(from.y, rect.y));
        dist = rect.x - (from.x + from.w);
        break;
      case 'left':
        isCandidate = rect.x + rect.w <= from.x + eps;
        overlap = Math.max(0, Math.min(from.y + from.h, rect.y + rect.h) - Math.max(from.y, rect.y));
        dist = from.x - (rect.x + rect.w);
        break;
      case 'down':
        isCandidate = rect.y >= from.y + from.h - eps;
        overlap = Math.max(0, Math.min(from.x + from.w, rect.x + rect.w) - Math.max(from.x, rect.x));
        dist = rect.y - (from.y + from.h);
        break;
      case 'up':
        isCandidate = rect.y + rect.h <= from.y + eps;
        overlap = Math.max(0, Math.min(from.x + from.w, rect.x + rect.w) - Math.max(from.x, rect.x));
        dist = from.y - (rect.y + rect.h);
        break;
    }

    if (isCandidate && overlap > 0) {
      if (overlap > bestOverlap || (overlap === bestOverlap && dist < bestDist)) {
        best = gid;
        bestOverlap = overlap;
        bestDist = dist;
      }
    }
  }

  return best;
}

// ---------------------------------------------------------------------------
// Drop zone calculation
// ---------------------------------------------------------------------------

/**
 * Determine which drop zone the cursor is in within a rect.
 * 25% edge bands; center otherwise.
 */
export function dropZoneFor(
  clientX: number,
  clientY: number,
  rect: DOMRect,
): DropZone {
  const rx = (clientX - rect.left) / rect.width;
  const ry = (clientY - rect.top) / rect.height;
  const d = Math.min(rx, 1 - rx, ry, 1 - ry);
  if (d > 0.25) return 'center';
  // Nearest edge wins
  const edges: [DropZone, number][] = [
    ['left', rx],
    ['right', 1 - rx],
    ['top', ry],
    ['bottom', 1 - ry],
  ];
  edges.sort((a, b) => a[1] - b[1]);
  return edges[0][0];
}

/** Only a new, explicitly focused reopen request may change the selected tab. */
export function shouldActivateReopenedPanel(panel: ToolPanel, previous?: ToolPanel): boolean {
  const state = panel.state.customState;
  const before = previous?.state.customState;
  return !!state && 'reopenedAt' in state && !!state.reopenedAt
    && 'reopenedWithFocus' in state && state.reopenedWithFocus === true
    && (!before || !('reopenedAt' in before) || before.reopenedAt !== state.reopenedAt);
}
